title: "My Personal Blog"
email: shpota.inna@yandex.ua
description: "Inna Shpota"
baseurl: "" # the subpath of your site, e.g. /blog
url: inna-shpota.com
copyright: "© Inna Shpota, 2017"
encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
